package graphic.management;

import config.Configuration;
import graphic.login.Login;
import graphic.management.listeners.OKButtonListener;
import graphic.management.listeners.SelectionListener;
import graphic.management.listeners.UpdateButtonListener;
import graphic.management.nodes.NodeFactory;
import logic.DefaultFactory;
import org.mongodb.morphia.Datastore;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.tree.*;
import java.awt.*;

/**
 * Created by kuujakke on 14.1.2017.
 */
public class ProjectManagement extends JPanel {
    private final Login login;
    private Configuration config;
    private JTree tree;
    private JScrollPane treePanel;
    private JPanel jPanel;
    private JTextField nameText;
    private JTextField descriptionText;
    private JTextArea deadlineText;
    private JTextArea completedText;
    private JTextArea createdText;
    private JButton updateButton;
    private JPanel updatePanel;
    private JSplitPane splitPane;
    private JComboBox cellFunction;
    private JButton oKButton;
    private JPanel editPanel;
    private JPanel functionPanel;
    private Datastore db;
    private DefaultFactory defaultFactory;
    private DefaultMutableTreeNode top;
    private NodeFactory nodeFactory;

    /**
     * Creates a new project management panel from login object.
     *
     * @param login Login
     */
    public ProjectManagement(Login login) {
        this.login = login;
        try {
            this.config = login.getConfig();
            this.db = login.getDatabase();
            this.defaultFactory = new DefaultFactory(this.config);
            this.nodeFactory = new NodeFactory(this.db, this.login.getLoginInformation().getProperty("db-name"));
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this.getParent(), e.toString());
            e.printStackTrace();
        }
        splitPane = new JSplitPane();
        splitPane.setResizeWeight(1);
        jPanel = new JPanel();
        jPanel.add(splitPane);
        $$$setupUI$$$();
        splitPane.setLeftComponent(treePanel);
        splitPane.setRightComponent(editPanel);
        GridBagConstraints c = new GridBagConstraints();
        c.fill = GridBagConstraints.NORTH;
        c.weightx = 1;
        c.weighty = 1;
        splitPane.setSize(config.getUIWidth() - 50, config.getUIHeight() - 100);
        splitPane.setPreferredSize(new Dimension(config.getUIWidth() - 50, config.getUIHeight() - 100));
        splitPane.setDividerLocation(0.7);
        jPanel.setSize(config.getUIWidth(), config.getUIHeight());
        jPanel.setPreferredSize(new Dimension(config.getUIWidth(), config.getUIHeight()));
        jPanel.add(splitPane, c);
        this.add(jPanel, c);
        this.setVisible(true);
        tree.addTreeSelectionListener(new SelectionListener(tree, nameText, descriptionText, createdText, deadlineText, completedText));
        updateButton.addActionListener(new UpdateButtonListener(tree, db, nameText, descriptionText, createdText, deadlineText, completedText));
        oKButton.addActionListener(new OKButtonListener(nodeFactory, tree, db, this.login, cellFunction, defaultFactory));
    }

    private void createUIComponents() {
        top = nodeFactory.createNodes();
        tree = new JTree(top);
        DefaultTreeModel model = new DefaultTreeModel(top);
        tree.setModel(model);
        tree.getSelectionModel().setSelectionMode(TreeSelectionModel.SINGLE_TREE_SELECTION);
        treePanel = new JScrollPane(tree);
        updatePanel = new JPanel();
        tree.repaint();
        tree.updateUI();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        jPanel.setLayout(new GridBagLayout());
        jPanel.setBorder(BorderFactory.createTitledBorder(null, "Projects", TitledBorder.CENTER, TitledBorder.DEFAULT_POSITION, new Font(jPanel.getFont().getName(), jPanel.getFont().getStyle(), jPanel.getFont().getSize())));
        splitPane.setContinuousLayout(false);
        splitPane.setDividerLocation(296);
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        jPanel.add(splitPane, gbc);
        splitPane.setLeftComponent(treePanel);
        tree.putClientProperty("JTree.lineStyle", "");
        tree.putClientProperty("html.disable", Boolean.FALSE);
        treePanel.setViewportView(tree);
        editPanel = new JPanel();
        editPanel.setLayout(new GridBagLayout());
        splitPane.setRightComponent(editPanel);
        functionPanel = new JPanel();
        functionPanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.ipadx = 1;
        gbc.ipady = 1;
        editPanel.add(functionPanel, gbc);
        functionPanel.setBorder(BorderFactory.createTitledBorder(null, "Edit", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-4473925)));
        oKButton = new JButton();
        oKButton.setText("OK");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.ipadx = 1;
        functionPanel.add(oKButton, gbc);
        cellFunction = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Add");
        defaultComboBoxModel1.addElement("Delete");
        cellFunction.setModel(defaultComboBoxModel1);
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        functionPanel.add(cellFunction, gbc);
        updatePanel.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridheight = 2;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        editPanel.add(updatePanel, gbc);
        updatePanel.setBorder(BorderFactory.createTitledBorder("Update"));
        final JLabel label1 = new JLabel();
        label1.setText("Deadline");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(1, 1, 1, 1);
        updatePanel.add(label1, gbc);
        final JLabel label2 = new JLabel();
        label2.setText("Time Completed");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 4;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(1, 1, 1, 1);
        updatePanel.add(label2, gbc);
        final JLabel label3 = new JLabel();
        label3.setText("Time Created");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 5;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(1, 1, 1, 1);
        updatePanel.add(label3, gbc);
        final JLabel label4 = new JLabel();
        label4.setText("Name");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(1, 1, 1, 1);
        updatePanel.add(label4, gbc);
        final JLabel label5 = new JLabel();
        label5.setText("Description");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(1, 1, 1, 1);
        updatePanel.add(label5, gbc);
        nameText = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(1, 1, 1, 1);
        updatePanel.add(nameText, gbc);
        descriptionText = new JTextField();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(1, 1, 1, 1);
        updatePanel.add(descriptionText, gbc);
        deadlineText = new JTextArea();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 3;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(1, 1, 1, 1);
        updatePanel.add(deadlineText, gbc);
        completedText = new JTextArea();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 4;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(1, 1, 1, 1);
        updatePanel.add(completedText, gbc);
        createdText = new JTextArea();
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 5;
        gbc.weightx = 0.5;
        gbc.fill = GridBagConstraints.BOTH;
        gbc.insets = new Insets(1, 1, 1, 1);
        updatePanel.add(createdText, gbc);
        updateButton = new JButton();
        updateButton.setText("Update");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 6;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        updatePanel.add(updateButton, gbc);
    }

    /**
     * IntelliJ GUI Builder did this.
     * @return JPanel
     */
    public JComponent $$$getRootComponent$$$() {
        return jPanel;
    }
}
